name: Generate Guilds Data

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # If there are any dependencies, install them here

    - name: Run Python script
      run: python gen_worlds_guilds.py

    - name: Commit and push if it changed
      run: |
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Automated job: ${timestamp}" || exit 0
        git push
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
