name: Generate Guilds Data
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_PAT }} 

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/Galarzaa90/tibia.py.git
        pip install requests

    - name: Run Python script
      run: python guild_data.py

    - name: Configure Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"

    - name: Commit and push if changes
      run: |
        git add world_guilds_data.json
        git diff --staged --quiet || git commit -m "Sanity check corrections for trolls list"
        git push || echo "No changes to commit"
